worj

diff --git a/.github/workflows/validate_pr_schema.yaml b/.github/workflows/validate_pr_schema.yaml
--- a/.github/workflows/validate_pr_schema.yaml
+++ b/.github/workflows/validate_pr_schema.yaml
@@ -16,5 +16,6 @@ jobs:
         shell: bash
         env:
           BODY: ${{ github.event.pull_request.body }}
-        run: echo "$BODY" | grep -q '^change: \(major\|minor\|patch\)$' || (echo "::error::Could Not Find Update SemVer Type" && exit 1)
+        run: |
+         echo "$BODY" | grep -q '^change: \(major\|minor\|patch\)$' || (echo "::error::Could Not Find Update SemVer Type" && exit 1)
 
